swagger: '2.0'
info:
  title: Discount Microservice API
  version: "0.1"
  description: Discount Microservice API for an E-Shop/Renting application
consumes:
  - application/json
produces:
  - application/json
basePath: "/api"
paths:
  /coupon/:
    post:
      tags: [ User Coupon ]
      operationId: app.test_add_coupon
      summary: Testing adding a coupon
      parameters:
        - $ref: '#/parameters/coupon_body'
      responses:
        200:
          description: Return status

  /coupons/:
    get:
      tags: [ User Coupon ]
      operationId: app.test_get_all_coupons
      summary: Testing the get function for all coupons
      responses:
        200:
          description: Return all coupons

  /coupon/{coupon_id}:
    get:
      tags: [ User Coupon ]
      operationId: app.test_get_coupon
      summary: Testing finding a coupon by id
      parameters:
        - $ref: '#/parameters/coupon_id'
      responses:
        200:
          description: Return coupon with the id specified

  /coupon/delete/{coupon_id}:
    delete:
      tags: [ User Coupon ]
      operationId: app.test_delete_coupon
      summary: Testing deleting a coupon by id
      parameters:
        - $ref: '#/parameters/coupon_id'
      responses:
        200:
          description: Delete coupon with the id specified

  /coupon/update/{coupon_id}:
    put:
      tags: [ User Coupon ]
      operationId: app.test_update_coupon
      summary: Testing an update to a coupon by ic
      parameters:
        - $ref: '#/parameters/coupon_id'
        - $ref: '#/parameters/coupon_put'
      responses:
        200:
          description: Update and return coupon with the id specified

  /coupon/{user_id}:
    get:
      tags: [ User Coupon ]
      operationId: app.test_get_coupon_for_user
      summary: Testing finding a coupon by user id
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return coupon with the user id specified

  /coupon/calculate_discount/:
    post:
      tags: [ User Coupon ]
      operationId: app.test_discount_calculation
      summary: Testing of the discount calculation for a coupon
      parameters:
        - $ref: '#/parameters/coupon_body_discount'
      responses:
        200:
          description: Return status

  /discount/renting/{discount_id}:
    get:
      tags: [ Renting Discounts ]
      operationId: app.get_renting_discount
      summary: Find renting discount by id
      parameters:
        - $ref: '#/parameters/discount_id'
      responses:
        200:
          description: Returned renting discount with the specified id

  /discount/renting/:
    get:
      tags: [ Renting Discounts ]
      operationId: app.get_all_renting_discounts
      summary: Get all renting discounts
      responses:
        200:
          description: Return all renting discounts

  /discount/renting:
    post:
      tags: [ Renting Discounts ]
      operationId: app.renting_discount_add
      summary: Adding new renting discount
      parameters:
        - $ref: '#/parameters/discount_body'
      responses:
        200:
          description: Return status

  /discount/renting/user/{user_id}:
    get:
      tags: [ Renting Discounts ]
      operationId: app.get_renting_discount_for_user
      summary: Get discount renting by user
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return renting discount with the user id specified

  /discount/renting/delete/{discount_id}:
    delete:
      tags: [ Renting Discounts ]
      operationId: app.renting_discount_delete
      summary: Deleting renting discount
      parameters:
        - $ref: '#/parameters/discount_id'
      responses:
        200:
          description: Delete renting discount with the specified id

  /discount/renting/update/{discount_id}:
    put:
      tags: [ Renting Discounts ]
      operationId: app.renting_discount_update
      summary: Update renting discount with given id
      parameters:
        - $ref: '#/parameters/discount_id'
        - $ref: '#/parameters/discount_put'
      responses:
        200:
          description: Update and return renting discount with the specified id

  /discount/buying/{discount_id}:
    get:
      tags: [ Buying Discounts ]
      operationId: app.get_buying_discount
      summary: Find renting discount by id
      parameters:
        - $ref: '#/parameters/discount_id'
      responses:
        200:
          description: Returned discount with the specified id

  /discount/buying/:
    get:
      tags: [ Buying Discounts ]
      operationId: app.get_all_buying_discounts
      summary: Get all buying discounts
      responses:
        200:
          description: Return all buying discounts

  /discount/buying:
    post:
      tags: [ Buying Discounts ]
      operationId: app.buying_discount_add
      summary: Adding new buying discount
      parameters:
        - $ref: '#/parameters/discount_body'
      responses:
        200:
          description: Return status

  /discount/buying/user/{user_id}:
    get:
      tags: [ Buying Discounts ]
      operationId: app.get_buying_discount_for_user
      summary: Get buying discount by user
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return buying discount with the user id specified

  /discount/buying/delete/{discount_id}:
    delete:
      tags: [ Buying Discounts ]
      operationId: app.buying_discount_delete
      summary: Deleting buying discount
      parameters:
        - $ref: '#/parameters/discount_id'
      responses:
        200:
          description: Delete buying discount with the specified id

  /discount/buying/update/{discount_id}:
    put:
      tags: [ Buying Discounts ]
      operationId: app.buying_discount_update
      summary: Update buying discount with given id
      parameters:
        - $ref: '#/parameters/discount_id'
        - $ref: '#/parameters/discount_put'
      responses:
        200:
          description: Update and return buying discount with the specified id

  /discount/parking/{discount_id}:
    get:
      tags: [ Parking Discounts ]
      operationId: app.get_parking_discount
      summary: Find parking discount by id
      parameters:
        - $ref: '#/parameters/discount_id'
      responses:
        200:
          description: Returned discount with the specified id

  /discount/parking/:
    get:
      tags: [ Parking Discounts ]
      operationId: app.get_all_parking_discounts
      summary: Get all parking discounts
      responses:
        200:
          description: Return all parking discounts

  /discount/parking:
    post:
      tags: [ Parking Discounts ]
      operationId: app.parking_discount_add
      summary: Adding new parking discount
      parameters:
        - $ref: '#/parameters/discount_body'
      responses:
        200:
          description: Return status

  /discount/parking/user/{user_id}:
    get:
      tags: [ Parking Discounts ]
      operationId: app.get_parking_discount_for_user
      summary: Get parking discount by user
      parameters:
        - $ref: '#/parameters/user_id'
      responses:
        200:
          description: Return parking discount with the user id specified

  /discount/parking/delete/{discount_id}:
    delete:
      tags: [ Parking Discounts ]
      operationId: app.parking_discount_delete
      summary: Deleting parking discount
      parameters:
        - $ref: '#/parameters/discount_id'
      responses:
        200:
          description: Delete parking discount with the specified id

  /discount/parking/update/{discount_id}:
    put:
      tags: [ Parking Discounts ]
      operationId: app.parking_discount_update
      summary: Update parking discount with given id
      parameters:
        - $ref: '#/parameters/discount_id'
        - $ref: '#/parameters/discount_put'
      responses:
        200:
          description: Update and return parking discount with the specified id
parameters:
  coupon_body:
    name: coupon_body
    description: Test for adding a coupon
    in: body
    schema:
      required:
        - Id
        - Type
        - UserId
      properties:
        Id:
          type: integer
        Type:
          type: string
        UserId:
          type: integer

  coupon_put:
    name: coupon_put
    description: Test for updating a coupon
    in: body
    schema:
      required:
        - UserId
        - Code
        - Amount
      properties:
        UserId:
          type: integer
        Code:
          type: string
        Amount:
          type: integer

  coupon_id:
    name: coupon_id
    description: The id of the coupon we are looking for
    in: path
    required: true
    type: integer

  discount_id:
    name: discount_id
    description: The id of the discount we are looking for
    in: path
    required: true
    type: integer

  discount_body:
    name: discount_body
    description: Adding a discount
    in: body
    schema:
      required:
        - discountRank_type
        - userId
      properties:
        discountRank_type:
          type: string
        userId:
          type: integer

  discount_put:
    name: discount_put
    description: Updating a discount
    in: body
    schema:
      required:
        - validFrom
        - validUntil
        - discountPercent
        - discountRank_type
        - code
      properties:
        validFrom:
          type: string
        validUntil:
          type: string
        discountPercent:
          type: number
        discountRank_type:
          type: string
        code:
          type: string

  user_id:
    name: user_id
    description: The id of the user we are looking for to find the coupon from
    in: path
    required: true
    type: integer # Nikola ova go smeniv od string vo integer, oti neli po dogovor rekovme deka ke bide integer id-to na user-ot

  coupon_body_discount:
    name: coupon_body_discount
    description: Test for calculating the discount for a coupon
    in: body
    schema:
      required:
        - UserId
        - InitialPrice
      properties:
        UserId:
          type: string
        InitialPrice:
          type: integer
