"""empty message

Revision ID: b5b0f7487958
Revises: 
Create Date: 2021-04-26 11:05:45.304062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5b0f7487958'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buying_discount',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('discountPercent', sa.Float(), nullable=False),
    sa.Column('discountRank_type', sa.Enum('BronzeParkingMedal', 'SilverParkingMedal', 'GoldParkingMedal', 'BronzeRentingMedal', 'SilverRentingMedal', 'GoldRentingMedal', 'Top10Monthly', 'Top3Annually', 'BronzeBuyingMedal', 'SilverBuyingMedal', 'GoldBuyingMedal', name='discountrank'), nullable=False),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validUntil', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parking_discount',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('discountPercent', sa.Float(), nullable=False),
    sa.Column('discountRank_type', sa.Enum('BronzeParkingMedal', 'SilverParkingMedal', 'GoldParkingMedal', 'BronzeRentingMedal', 'SilverRentingMedal', 'GoldRentingMedal', 'Top10Monthly', 'Top3Annually', 'BronzeBuyingMedal', 'SilverBuyingMedal', 'GoldBuyingMedal', name='discountrank'), nullable=False),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validUntil', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('TimesBought', sa.Integer(), nullable=False),
    sa.Column('ValidFrom', sa.DateTime(), nullable=False),
    sa.Column('ValidTo', sa.DateTime(), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('DiscountPercentage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('renting_discount',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('userId', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=15), nullable=False),
    sa.Column('discountPercent', sa.Float(), nullable=False),
    sa.Column('discountRank_type', sa.Enum('BronzeParkingMedal', 'SilverParkingMedal', 'GoldParkingMedal', 'BronzeRentingMedal', 'SilverRentingMedal', 'GoldRentingMedal', 'Top10Monthly', 'Top3Annually', 'BronzeBuyingMedal', 'SilverBuyingMedal', 'GoldBuyingMedal', name='discountrank'), nullable=False),
    sa.Column('validFrom', sa.DateTime(), nullable=False),
    sa.Column('validUntil', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_coupon',
    sa.Column('Id', sa.BigInteger(), nullable=False),
    sa.Column('UserId', sa.BigInteger(), nullable=False),
    sa.Column('Code', sa.String(length=15), nullable=False),
    sa.Column('ValidFrom', sa.DateTime(), nullable=False),
    sa.Column('ValidTo', sa.DateTime(), nullable=False),
    sa.Column('Type', sa.String(), nullable=False),
    sa.Column('Amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_coupon')
    op.drop_table('renting_discount')
    op.drop_table('product')
    op.drop_table('parking_discount')
    op.drop_table('buying_discount')
    # ### end Alembic commands ###
